CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUBSCRIBER_NAME VARCHAR2(30) NOT NULL,
    DATE_SUBSCRIBED DATE NOT NULL,
    DATE_RETURNED DATE,
    BOOK_ID BIGINT
);
